/* Copyright 2014 Google */ (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var g,aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={a:!0},ea={};try{ea.__proto__=da;ca=ea.a;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var fa=ba,ha=function(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.s=b.prototype},p=this||self,u=function(){},ia=function(a){a.ha=void 0;a.$=function(){return a.ha?a.ha:a.ha=new a}},ja=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},ka=function(a){var b=ja(a);return"array"==b||"object"==
b&&"number"==typeof a.length},v=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},na=function(a){return Object.prototype.hasOwnProperty.call(a,la)&&a[la]||(a[la]=++ma)},la="closure_uid_"+(1E9*Math.random()>>>0),ma=0,oa=function(a,b,c){return a.call.apply(a.bind,arguments)},pa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,
e)}}return function(){return a.apply(b,arguments)}},x=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?x=oa:x=pa;return x.apply(null,arguments)},y=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}},A=function(a,b){function c(){}c.prototype=b.prototype;a.s=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Id=function(d,e,f){for(var h=Array(arguments.length-
2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}},qa=function(a){return a};function ra(a){a=String(a).toLowerCase().replace("_","-");if("zh-cn"==a)return"zh-CN";if("zh-tw"==a)return"zh-TW";var b=a.indexOf("-");a=0<=b?a.substring(0,b):a;return"zh"==a?"zh-CN":a}function B(a){a=chrome.i18n.getMessage(a);return chrome.i18n.getMessage(a)};function sa(a){if(Error.captureStackTrace)Error.captureStackTrace(this,sa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}A(sa,Error);sa.prototype.name="CustomError";var ta;var ua=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");sa.call(this,c+a[d])};A(ua,sa);ua.prototype.name="AssertionError";
var va=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new ua(""+e,f||[]);},C=function(a,b,c){a||va("",null,b,Array.prototype.slice.call(arguments,2));return a},wa=function(a,b){throw new ua("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},xa=function(a,b,c){"number"!==typeof a&&va("Expected number but got %s: %s.",[ja(a),a],b,Array.prototype.slice.call(arguments,2));return a},ya=function(a,b,c){"string"!==typeof a&&va("Expected string but got %s: %s.",
[ja(a),a],b,Array.prototype.slice.call(arguments,2));return a},za=function(a,b,c){v(a)||va("Expected object but got %s: %s.",[ja(a),a],b,Array.prototype.slice.call(arguments,2))},Aa=function(a,b,c){v(a)&&1==a.nodeType||va("Expected Element but got %s: %s.",[ja(a),a],b,Array.prototype.slice.call(arguments,2))},Ca=function(a,b,c,d){a instanceof b||va("Expected instanceof %s but got %s.",[Ba(b),Ba(a)],c,Array.prototype.slice.call(arguments,3))},Ba=function(a){return a instanceof Function?a.displayName||
a.name||"unknown type name":a instanceof Object?a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a):null===a?"null":typeof a};var Da;var Ga=function(a,b){this.g=a===Ea&&b||"";this.h=Fa};Ga.prototype.Wa=!0;Ga.prototype.Ba=function(){return this.g};Ga.prototype.toString=function(){return"Const{"+this.g+"}"};var Ha=function(a){if(a instanceof Ga&&a.constructor===Ga&&a.h===Fa)return a.g;wa("expected object of type Const, got '"+a+"'");return"type_error:Const"},Fa={},Ea={};var Ia=Array.prototype.indexOf?function(a,b){C(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ja=Array.prototype.forEach?function(a,b,c){C(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
function Ka(a,b){return 0<=Ia(a,b)}function La(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ma(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(ka(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}}function Na(a,b,c,d){C(null!=a.length);Array.prototype.splice.apply(a,Oa(arguments,1))}
function Oa(a,b,c){C(null!=a.length);return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var Pa=function(a){return/^[\s\xa0]*$/.test(a)},Qa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Ra=/&/g,Sa=/</g,Ta=/>/g,Ua=/"/g,Va=/'/g,Wa=/\x00/g,Xa=/[\x00&<>"']/,Za=function(a,b){var c=0;a=Qa(String(a)).split(".");b=Qa(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&
0==h[0].length)break;c=Ya(0==f[1].length?0:parseInt(f[1],10),0==h[1].length?0:parseInt(h[1],10))||Ya(0==f[2].length,0==h[2].length)||Ya(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c},Ya=function(a,b){return a<b?-1:a>b?1:0};function D(){var a=p.navigator;return a&&(a=a.userAgent)?a:""}function G(a){return-1!=D().indexOf(a)};function $a(){return G("Firefox")||G("FxiOS")}function ab(){return(G("Chrome")||G("CriOS"))&&!G("Edge")||G("Silk")};function bb(){return G("iPhone")&&!G("iPod")&&!G("iPad")}function cb(){return bb()||G("iPad")||G("iPod")};var db=function(a){db[" "](a);return a};db[" "]=u;var eb=function(a,b){try{return db(a[b]),!0}catch(c){}return!1},gb=function(a,b){var c=fb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var hb=G("Opera"),H=G("Trident")||G("MSIE"),ib=G("Edge"),jb=ib||H,I=G("Gecko")&&!(-1!=D().toLowerCase().indexOf("webkit")&&!G("Edge"))&&!(G("Trident")||G("MSIE"))&&!G("Edge"),K=-1!=D().toLowerCase().indexOf("webkit")&&!G("Edge"),L=G("Macintosh"),kb=G("Windows"),lb=G("Android"),mb=bb(),nb=G("iPad"),ob=G("iPod"),pb=cb(),qb=function(){var a=p.document;return a?a.documentMode:void 0},rb;
a:{var sb="",tb=function(){var a=D();if(I)return/rv:([^\);]+)(\)|;)/.exec(a);if(ib)return/Edge\/([\d\.]+)/.exec(a);if(H)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(K)return/WebKit\/(\S+)/.exec(a);if(hb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();tb&&(sb=tb?tb[1]:"");if(H){var ub=qb();if(null!=ub&&ub>parseFloat(sb)){rb=String(ub);break a}}rb=sb}var vb=rb,fb={},wb=function(a){return gb(a,function(){return 0<=Za(vb,a)})},xb;
if(p.document&&H){var yb=qb();xb=yb?yb:parseInt(vb,10)||void 0}else xb=void 0;var zb=xb;function Ab(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Bb(a,b){for(var c in a)if(a[c]==b)return!0;return!1}var Cb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Db(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Cb.length;f++)c=Cb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}
function Eb(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return Eb.apply(null,arguments[0]);if(b%2)throw Error("Uneven number of arguments");for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};var Fb={},M=function(a,b,c){this.h=c===Fb?a:"";this.g=b;this.Wa=this.i=!0};M.prototype.Ba=function(){return this.h.toString()};M.prototype.toString=function(){return this.h.toString()};
var Gb=function(a){if(a instanceof M&&a.constructor===M)return a.h;wa("expected object of type SafeHtml, got '"+a+"' of type "+ja(a));return"type_error:SafeHtml"},Ib=function(a){if(a instanceof M)return a;var b="object"==typeof a,c=null;b&&a.i&&(c=a.g);a=b&&a.Wa?a.Ba():String(a);Xa.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(Ra,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(Sa,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(Ta,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(Ua,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(Va,
"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(Wa,"&#0;")));return Hb(a,c)},Jb=function(a){if(a instanceof M)return a;a=Ib(a);return Hb(Gb(a).toString().replace(/(\r\n|\r|\n)/g,"<br>"),a.g)},Hb=function(a,b){if(void 0===Da){var c=null;var d=p.trustedTypes;if(d&&d.createPolicy){try{c=d.createPolicy("goog#html",{createHTML:qa,createScript:qa,createScriptURL:qa})}catch(e){p.console&&p.console.error(e.message)}Da=c}else Da=c}a=(c=Da)?c.createHTML(a):a;return new M(a,b,Fb)},Kb=new M(p.trustedTypes&&p.trustedTypes.emptyHTML||
"",0,Fb);var Lb=function(a,b,c){ya(Ha(a),"must provide justification");C(!Pa(Ha(a)),"must provide non-empty justification");return Hb(b,c||null)};var Mb={MATH:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0},Nb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if("undefined"===typeof document)return!1;var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);if(!a.firstChild)return!1;b=a.firstChild.firstChild;a.innerHTML=Gb(Kb);return!b.parentElement}),Ob=function(a,b){if(Nb())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=Gb(b)};var N=function(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0};N.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var Pb=function(a,b){return new N(a.x-b.x,a.y-b.y)};N.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};N.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};N.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
N.prototype.translate=function(a,b){a instanceof N?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),"number"===typeof b&&(this.y+=b));return this};var Qb=function(a,b){this.width=a;this.height=b};g=Qb.prototype;g.toString=function(){return"("+this.width+" x "+this.height+")"};g.aspectRatio=function(){return this.width/this.height};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Tb=function(a){return-1!=a.indexOf("&")?"document"in p?Rb(a):Sb(a):a},Rb=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'};var c=p.document.createElement("div");return a.replace(Ub,function(d,e){var f=b[d];if(f)return f;"#"==e.charAt(0)&&(e=Number("0"+e.substr(1)),isNaN(e)||(f=String.fromCharCode(e)));if(!f){f=Lb(new Ga(Ea,"Single HTML entity."),d+" ");if(c.tagName&&Mb[c.tagName.toUpperCase()])throw Error("goog.dom.safe.setInnerHtml cannot be used to set content of "+c.tagName+
".");Ob(c,f);f=c.firstChild.nodeValue.slice(0,-1)}return b[d]=f})},Sb=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:return"#"!=c.charAt(0)||(c=Number("0"+c.substr(1)),isNaN(c))?b:String.fromCharCode(c)}})},Ub=/&([^;\s<&]+);?/g,Vb=function(a){return null==a?"":String(a)};var P=function(a){return a?new Wb(O(a)):ta||(ta=new Wb)},Q=function(a){return Xb(document,a)},Xb=function(a,b){return"string"===typeof b?a.getElementById(b):b},Zb=function(a){var b=a||document;return b.querySelectorAll&&b.querySelector?b.querySelectorAll(".jfk-tooltip-data"):Yb(document,"jfk-tooltip-data",a)},$b=function(a,b){var c=b||document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):
Yb(c,a,b)[0]||null}return a||null},Yb=function(a,b,c){var d;a=c||a;if(a.querySelectorAll&&a.querySelector&&b)return a.querySelectorAll(b?"."+b:"");if(b&&a.getElementsByClassName){var e=a.getElementsByClassName(b);return e}e=a.getElementsByTagName("*");if(b){var f={};for(c=d=0;a=e[c];c++){var h=a.className;"function"==typeof h.split&&Ka(h.split(/\s+/),b)&&(f[d++]=a)}f.length=d;return f}return e},bc=function(a,b){Ab(b,function(c,d){c&&"object"==typeof c&&c.Wa&&(c=c.Ba());"style"==d?a.style.cssText=
c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:ac.hasOwnProperty(d)?a.setAttribute(ac[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},ac={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},ec=function(a){var b=cc(a);a=dc(a);return H&&wb("10")&&a.pageYOffset!=b.scrollTop?
new N(b.scrollLeft,b.scrollTop):new N(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)},cc=function(a){return a.scrollingElement?a.scrollingElement:!K&&fc(a)?a.documentElement:a.body||a.documentElement},dc=function(a){return a.parentWindow||a.defaultView},hc=function(a,b,c){return gc(document,arguments)},gc=function(a,b){var c=b[1],d=ic(a,String(b[0]));c&&("string"===typeof c?d.className=c:Array.isArray(c)?d.className=c.join(" "):bc(d,c));2<b.length&&jc(a,d,b,2);return d},jc=function(a,b,c,
d){function e(k){k&&b.appendChild("string"===typeof k?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];if(!ka(f)||v(f)&&0<f.nodeType)e(f);else{a:{if(f&&"number"==typeof f.length){if(v(f)){var h="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){h="function"==typeof f.item;break a}}h=!1}Ja(h?La(f):f,e)}}},ic=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},fc=function(a){return"CSS1Compat"==a.compatMode},
kc=function(a,b){jc(O(a),a,arguments,1)},lc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},mc=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)},nc=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},O=function(a){C(a,"Node cannot be null or undefined.");return 9==a.nodeType?a:a.ownerDocument||a.document},R=
function(a,b){C(null!=a,"goog.dom.setTextContent expects a non-null value for node");if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(C(a.lastChild));a.firstChild.data=String(b)}else{lc(a);var c=O(a);a.appendChild(c.createTextNode(String(b)))}},oc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},pc={IMG:" ",BR:"\n"},qc=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))},
rc=function(a){a=a.tabIndex;return"number"===typeof a&&0<=a&&32768>a},tc=function(a){var b=[];sc(a,b,!1);return b.join("")},sc=function(a,b,c){if(!(a.nodeName in oc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in pc)b.push(pc[a.nodeName]);else for(a=a.firstChild;a;)sc(a,b,c),a=a.nextSibling},uc=function(a,b){for(var c=0;a;){C("parentNode"!=a.name);if(b(a))return a;a=a.parentNode;c++}return null},Wb=function(a){this.g=a||p.document||
document};g=Wb.prototype;g.j=function(a){return Xb(this.g,a)};g.setProperties=bc;g.Z=function(a,b,c){return gc(this.g,arguments)};g.sb=kc;g.getChildren=function(a){return void 0!=a.children?a.children:Array.prototype.filter.call(a.childNodes,function(b){return 1==b.nodeType})};g.contains=nc;/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
var wc=function(){this.l=[];chrome.i18n.getAcceptLanguages(x(this.u,this));this.g="";this.h="1";this.i=!0;this.m={};chrome.storage.local.get(null,x(this.G,this));vc(this)};wc.prototype.G=function(a){"gtxTargetLang"in a&&(this.g=a.gtxTargetLang);"gtxShowBubble"in a&&(this.h=a.gtxShowBubble);"gtxDetectLanguage"in a&&(this.i=a.gtxDetectLanguage);"gtxSourceLangList"in a&&xc(this,a.gtxSourceLangList);"gtxTargetLangList"in a&&(this.m=xc(this,a.gtxTargetLangList));this.loaded=!0};
var xc=function(a,b){var c=[],d;for(d in b)c.push({code:d,name:b[d]});c.sort(a.o);a={};for(b=0;b<c.length;b++)a[c[b].code]=c[b].name;return a};wc.prototype.o=function(a,b){return a.name.localeCompare(b.name)};var yc=function(a){var b={};b.gtxTargetLang=a.g;b.gtxShowBubble=a.h;b.gtxDetectLanguage=a.i;chrome.storage.local.set(b)},vc=function(a){chrome.storage.onChanged.addListener(function(b){b.gtxTargetLang&&(a.g=b.gtxTargetLang.newValue);b.gtxShowBubble&&(a.h=b.gtxShowBubble.newValue)})};
wc.prototype.u=function(a){this.l=a};var zc=!!chrome.i18n.detectLanguage;/*

 SPDX-License-Identifier: Apache-2.0
*/
var Ac={Kd:!0},Bc={Jd:!0},Cc=function(){throw Error("Do not instantiate directly");};Cc.prototype.za=null;Cc.prototype.getContent=function(){return this.content};Cc.prototype.toString=function(){return this.content};var Dc=function(){Cc.call(this)};A(Dc,Cc);Dc.prototype.ta=Ac;var Ec=function(){Cc.call(this)};A(Ec,Cc);Ec.prototype.ta=Bc;Ec.prototype.za=1;var Fc=function(a,b,c){(b=null!=a&&a.ta===b)&&C(a.constructor===c);return b};var Gc=Object.freeze||function(a){return a};var Hc=function(a){if(null!=a)switch(a.za){case 1:return 1;case -1:return-1;case 0:return 0}return null},Lc=function(a){return Fc(a,Ac,Dc)?a:a instanceof M?Ic(Gb(a).toString(),a.g):Ic(String(String(a)).replace(Jc,Kc),Hc(a))},Ic=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.za=d);return c}}(Dc),Mc={},S=function(a){if(Fc(a,Ac,Dc)){var b=String;a=a.getContent();a=String(a).replace(Oc,"").replace(Pc,"&lt;");b=b(a).replace(Qc,Kc)}else b=
String(a).replace(Jc,Kc);return b},Sc=function(a){Fc(a,Bc,Ec)?a=a.getContent():(a=String(a),Rc.test(a)||(wa("Bad value `%s` for |filterHtmlAttributes",[a]),a="zSoyz"));return a},Tc=function(a){Fc(a,Bc,Ec)&&(a=a.getContent());var b;if(b=a)b=!(1<=a.length&&" "===a.substring(0,1));return(b?" ":"")+a},Uc={},Vc=function(){C(Uc===Uc,"found an incorrect call marker, was an internal function called from the top level?")},Wc={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;",
" ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"},Kc=function(a){return Wc[a]},Jc=/[\x00\x22\x26\x27\x3c\x3e]/g,Qc=/[\x00\x22\x27\x3c\x3e]/g,Rc=/^(?!on|src|(?:action|archive|background|cite|classid|codebase|content|data|dsync|href|http-equiv|longdesc|style|usemap)\s*$)(?:[a-z0-9_$:-]*)$/i,Oc=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,
Pc=/</g;/*
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function Xc(a,b,c){a=a(b||Yc,void 0);c=ic((c||P()).g,"DIV");if(v(a))if(a instanceof Cc){if(a.ta!==Ac)throw Error("Sanitized content was not of kind HTML.");a=Lb(new Ga(Ea,"Soy SanitizedContent of kind HTML produces SafeHtml-contract-compliant value."),a.toString(),a.za)}else wa("Soy template output is unsafe for use as HTML: "+a),a=Ib("zSoyz");else a=Ib(String(a));b=a.Ba();var d=b.match(Zc);C(!d,"This template starts with a %s, which cannot be a child of a <div>, as required by soy internals. Consider using goog.soy.renderElement instead.\nTemplate output: %s",
d&&d[0],b);Ob(c,a);1==c.childNodes.length&&(a=c.firstChild,1==a.nodeType&&(c=a));return c}var Zc=/^<(body|caption|col|colgroup|head|html|tr|td|th|tbody|thead|tfoot)>/i,Yc={};var $c=function(a,b){if(Mc["jfk.templates.button.strict"])return Mc["jfk.templates.button.strict"](a,b);a=a||{};var c=a.attributes,d=a.content,e=a.disabled,f=a.id,h=a.ob,k=a.title,l=a.Ib,q=a.value,n=Ic;f='<div role="button"'+(f?' id="'+S(f)+'"':"")+' class="';var m=a||{};a=m.sa;var t=m.disabled,w=m.checked,r=m.style;m=m.width;Vc();if(Mc["jfk.templates.button.classes_"])b=Mc["jfk.templates.button.classes_"]({sa:a,disabled:t,checked:w,style:r,width:m},b);else{b="goog-inline-block jfk-button ";switch(v(r)?
r.toString():r){case 0:b+="jfk-button-standard";break;case 2:b+="jfk-button-action";break;case 3:b+="jfk-button-primary";break;case 1:b+="jfk-button-default";break;case 4:b+="jfk-button-flat";break;case 5:b+="jfk-button-mini";break;case 6:b+="jfk-button-contrast";break;default:b+="jfk-button-standard"}b+=((m&&m.Hb&&(1).Hb?m.ta!==(1).ta?0:m.toString()===(1).toString():1==m)?" jfk-button-narrow":"")+(w?" jfk-button-checked":"")+(a?" "+a:"")+(t?" jfk-button-disabled":"")}return n(f+S(b)+'"'+(e?' aria-disabled="true"':
' tabindex="'+(h?S(h):"0")+'"')+(k?l?' data-tooltip="'+S(k)+'"':' title="'+S(k)+'"':"")+(q?' value="'+S(q)+'"':"")+(c?Tc(Sc(c)):"")+">"+Lc(null!=d?d:"")+"</div>")};C(!0);var ad=$a(),bd=bb()||G("iPod"),cd=G("iPad"),dd=G("Android")&&!(ab()||$a()||G("Opera")||G("Silk")),ed=ab(),fd=G("Safari")&&!(ab()||G("Coast")||G("Opera")||G("Edge")||G("Edg/")||G("OPR")||$a()||G("Silk")||G("Android"))&&!cb();var gd="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol("INTERNAL_ARRAY_STATE"):void 0;var hd=Object,id=hd.freeze,jd=[];(function(a,b,c){Array.isArray(a)||va("Expected array but got %s: %s.",[ja(a),a],b,Array.prototype.slice.call(arguments,2))})(jd,"state is only maintained on arrays.");Object.isFrozen(jd)||(gd?jd[gd]|=1:void 0!==jd.g?jd.g|=1:Object.defineProperties(jd,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));id.call(hd,jd);var kd=function(a){return"string"==typeof a.className?a.className:a.getAttribute&&a.getAttribute("class")||""},ld=function(a){return a.classList?a.classList:kd(a).match(/\S+/g)||[]},md=function(a,b){"string"==typeof a.className?a.className=b:a.setAttribute&&a.setAttribute("class",b)},nd=function(a,b){return a.classList?a.classList.contains(b):Ka(ld(a),b)},od=function(a,b){if(a.classList)a.classList.add(b);else if(!nd(a,b)){var c=kd(a);md(a,c+(0<c.length?" "+b:b))}},pd=function(a,b){if(a.classList)Array.prototype.forEach.call(b,
function(e){od(a,e)});else{var c={};Array.prototype.forEach.call(ld(a),function(e){c[e]=!0});Array.prototype.forEach.call(b,function(e){c[e]=!0});b="";for(var d in c)b+=0<b.length?" "+d:d;md(a,b)}},qd=function(a,b){a.classList?a.classList.remove(b):nd(a,b)&&md(a,Array.prototype.filter.call(ld(a),function(c){return c!=b}).join(" "))},rd=function(a,b){a.classList?Array.prototype.forEach.call(b,function(c){qd(a,c)}):md(a,Array.prototype.filter.call(ld(a),function(c){return!Ka(b,c)}).join(" "))};var sd=function(){};sd.prototype.o=function(){};var td=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};g=td.prototype;g.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};g.contains=function(a){return this&&a?a instanceof td?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
g.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.translate=function(a,b){a instanceof N?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(xa(a),this.left+=a,this.right+=a,"number"===typeof b&&(this.top+=b,this.bottom+=b));return this};var ud=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};g=ud.prototype;g.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};g.contains=function(a){return a instanceof N?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};
g.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};g.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.translate=function(a,b){a instanceof N?(this.left+=a.x,this.top+=a.y):(this.left+=xa(a),"number"===typeof b&&(this.top+=b));return this};var vd=function(a,b){var c=O(a);return c.defaultView&&c.defaultView.getComputedStyle&&(a=c.defaultView.getComputedStyle(a,null))?a[b]||a.getPropertyValue(b)||"":""},wd=function(a,b){return vd(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]},yd=function(a,b,c){if(b instanceof N){var d=b.x;b=b.y}else d=b,b=c;a.style.left=xd(d);a.style.top=xd(b)},zd=function(a){try{return a.getBoundingClientRect()}catch(b){return{left:0,top:0,right:0,bottom:0}}},Ad=function(a){if(H&&!(8<=Number(zb)))return C(a&&
"offsetParent"in a),a.offsetParent;var b=O(a),c=wd(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(11==a.nodeType&&a.host&&(a=a.host),c=wd(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null},Cd=function(a){for(var b=new td(0,Infinity,Infinity,0),c=P(a),d=c.g.body,e=c.g.documentElement,f=cc(c.g);a=Ad(a);)if(!(H&&0==a.clientWidth||
K&&0==a.clientHeight&&a==d)&&a!=d&&a!=e&&"visible"!=wd(a,"overflow")){var h=Bd(a),k=new N(a.clientLeft,a.clientTop);h.x+=k.x;h.y+=k.y;b.top=Math.max(b.top,h.y);b.right=Math.min(b.right,h.x+a.clientWidth);b.bottom=Math.min(b.bottom,h.y+a.clientHeight);b.left=Math.max(b.left,h.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=(dc(c.g)||window).document;c=fc(c)?c.documentElement:c.body;c=new Qb(c.clientWidth,c.clientHeight);b.right=Math.min(b.right,d+c.width);b.bottom=
Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null},Bd=function(a){var b=O(a);za(a,"Parameter is required");var c=new N(0,0);var d=b?O(b):document;d=!H||9<=Number(zb)||fc(P(d).g)?d.documentElement:d.body;if(a==d)return c;a=zd(a);b=ec(P(b).g);c.x=a.left+b.x;c.y=a.top+b.y;return c},Ed=function(a,b){a=Dd(a);b=Dd(b);return new N(a.x-b.x,a.y-b.y)},Fd=function(a){a=zd(a);return new N(a.left,a.top)},Dd=function(a){C(a);if(1==a.nodeType)return Fd(a);a=a.changedTouches?
a.changedTouches[0]:a;return new N(a.clientX,a.clientY)},xd=function(a){"number"==typeof a&&(a+="px");return a},Hd=function(a){var b=Gd;if("none"!=wd(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a},Gd=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=K&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=zd(a),new Qb(a.right-a.left,a.bottom-a.top)):
new Qb(b,c)},Id=function(a){var b=Bd(a);a=Hd(a);return new ud(b.x,b.y,a.width,a.height)},Jd=function(a){return"rtl"==wd(a,"direction")},Kd=I?"MozUserSelect":K||ib?"WebkitUserSelect":null,Ld=function(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;b=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+b},Md=function(a,b){return(b=a.currentStyle?a.currentStyle[b]:null)?Ld(a,b):0},Nd={thin:2,medium:4,
thick:6},Od=function(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;b=a.currentStyle?a.currentStyle[b+"Width"]:null;return b in Nd?Nd[b]:Ld(a,b)};var Pd=function(){if(kb){var a=/Windows NT ([0-9.]+)/;return(a=a.exec(D()))?a[1]:"0"}return L?(a=/1[0|1][_.][0-9_.]+/,(a=a.exec(D()))?a[0].replace(/_/g,"."):"10"):lb?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(D()))?a[1]:""):mb||nb||ob?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(D()))?a[1].replace(/_/g,"."):""):""}();var Qd=function(a){return(a=a.exec(D()))?a[1]:""},Rd=function(){if(ad)return Qd(/Firefox\/([0-9.]+)/);if(H||ib||hb)return vb;if(ed){if(cb()||G("Macintosh")){var a=Qd(/CriOS\/([0-9.]+)/);if(a)return a}return Qd(/Chrome\/([0-9.]+)/)}if(fd&&!cb())return Qd(/Version\/([0-9.]+)/);if(bd||cd){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(D()))return a[1]+"."+a[2]}else if(dd)return(a=Qd(/Android\s+([0-9.]+)/))?a:Qd(/Version\/([0-9.]+)/);return""}();var Sd=function(a,b){return(b&8&&Jd(a)?b^4:b)&-9};var Td=function(a,b){this.i=a;this.u=!!b;this.l={0:this.i+"-arrowright",1:this.i+"-arrowup",2:this.i+"-arrowdown",3:this.i+"-arrowleft"}};ha(Td,sd);Td.prototype.o=function(){C(this.m,"Must call setElements first.");var a=this.Sa;2==a&&(a=0);Ud(this,this.Ta,a,2==this.Sa?Vd(this.Ta)?this.g.offsetHeight/2:this.g.offsetWidth/2:20,0,void 0)};
var Ud=function(a,b,c,d,e,f){if(a.h){var h=Wd(b,c),k=a.h;var l=Hd(k);l=(Vd(b)?l.height/2:l.width/2)-d;var q=Sd(k,h),n;if(n=Cd(k))k=Id(k),k=new td(k.top,k.left+k.width,k.top+k.height,k.left),Vd(b)?k.top<n.top&&!(q&1)?l-=n.top-k.top:k.bottom>n.bottom&&q&1&&(l-=k.bottom-n.bottom):k.left<n.left&&!(q&4)?l-=n.left-k.left:k.right>n.right&&q&4&&(l-=k.right-n.right);n=Vd(b)?new N(a.Ya,l):new N(l,a.Ya);q=Vd(b)?6:9;a.Qa&&2==e&&(q=Vd(b)?4:1);l=b^3;Vd(b)&&"rtl"==a.h.dir&&(l=b);k=a.h;var m=Wd(l,c);l=a.g;q=a.nb?
q:0;C(l);var t=l.offsetParent;if(t){var w="HTML"==t.tagName||"BODY"==t.tagName;if(!w||"static"!=wd(t,"position")){var r=Bd(t);if(!w){w=Jd(t);var E;if(E=w){E=fd&&0<=Za(Rd,10);var J;if(J=pb)J=0<=Za(Pd,10);var F=ed&&0<=Za(Rd,85);E=I||E||J||F}w=E?-t.scrollLeft:w&&!jb&&"visible"!=wd(t,"overflowX")?t.scrollWidth-t.clientWidth-t.scrollLeft:t.scrollLeft;r=Pb(r,new N(w,t.scrollTop))}}}r=r||new N;t=Id(k);if(w=Cd(k))F=new ud(w.left,w.top,w.right-w.left,w.bottom-w.top),w=Math.max(t.left,F.left),E=Math.min(t.left+
t.width,F.left+F.width),w<=E&&(J=Math.max(t.top,F.top),F=Math.min(t.top+t.height,F.top+F.height),J<=F&&(t.left=w,t.top=J,t.width=E-w,t.height=F-J));w=P(k);J=P(l);if(w.g!=J.g){E=w.g.body;J=dc(J.g);F=new N(0,0);var X=(X=O(E))?dc(X):window;if(eb(X,"parent")){var Nc=E;do{var he=X==J?Bd(Nc):Fd(C(Nc));F.x+=he.x;F.y+=he.y}while(X&&X!=J&&X!=X.parent&&(Nc=X.frameElement)&&(X=X.parent))}E=Pb(F,Bd(E));!H||9<=Number(zb)||fc(w.g)||(E=Pb(E,ec(w.g)));t.left+=E.x;t.top+=E.y}k=Sd(k,m);m=t.left;k&4?m+=t.width:k&2&&
(m+=t.width/2);m=new N(m,t.top+(k&1?t.height:0));m=Pb(m,r);n&&(m.x+=(k&4?-1:1)*n.x,m.y+=(k&1?-1:1)*n.y);var z;q&&(z=Cd(l))&&(z.top-=r.y,z.right-=r.x,z.bottom-=r.y,z.left-=r.x);k=m;n=z;k=new N(k.x,k.y);m=Sd(l,h);z=Hd(l);r=new Qb(z.width,z.height);h=k;k=r;h=new N(h.x,h.y);k=new Qb(k.width,k.height);r=0;if(f||0!=m)m&4?h.x-=k.width+(f?f.right:0):m&2?h.x-=k.width/2:f&&(h.x+=f.left),m&1?h.y-=k.height+(f?f.bottom:0):f&&(h.y+=f.top);q&&(n?(m=h,r=k,t=0,65==(q&65)&&(m.x<n.left||m.x>=n.right)&&(q&=-2),132==
(q&132)&&(m.y<n.top||m.y>=n.bottom)&&(q&=-5),m.x<n.left&&q&1&&(m.x=n.left,t|=1),q&16&&(w=m.x,m.x<n.left&&(m.x=n.left,t|=4),m.x+r.width>n.right&&(r.width=Math.min(n.right-m.x,w+r.width-n.left),r.width=Math.max(r.width,0),t|=4)),m.x+r.width>n.right&&q&1&&(m.x=Math.max(n.right-r.width,n.left),t|=1),q&2&&(t|=(m.x<n.left?16:0)|(m.x+r.width>n.right?32:0)),m.y<n.top&&q&4&&(m.y=n.top,t|=2),q&32&&(w=m.y,m.y<n.top&&(m.y=n.top,t|=8),m.y+r.height>n.bottom&&(r.height=Math.min(n.bottom-m.y,w+r.height-n.top),r.height=
Math.max(r.height,0),t|=8)),m.y+r.height>n.bottom&&q&4&&(m.y=Math.max(n.bottom-r.height,n.top),t|=2),q&8&&(t|=(m.y<n.top?64:0)|(m.y+r.height>n.bottom?128:0)),q=t):q=256,r=q);q=new ud(0,0,0,0);q.left=h.x;q.top=h.y;q.width=k.width;q.height=k.height;h=r;h&496||(yd(l,new N(q.left,q.top)),r=new Qb(q.width,q.height),z==r||z&&r&&z.width==r.width&&z.height==r.height||(z=r,q=O(l),n=fc(P(q).g),!H||wb("10")||n?(l=l.style,I?l.MozBoxSizing="border-box":K?l.WebkitBoxSizing="border-box":l.boxSizing="border-box",
l.width=Math.max(z.width,0)+"px",l.height=Math.max(z.height,0)+"px"):(q=l.style,n?(H?(n=Md(l,"paddingLeft"),k=Md(l,"paddingRight"),m=Md(l,"paddingTop"),r=Md(l,"paddingBottom"),n=new td(m,k,r,n)):(n=vd(l,"paddingLeft"),k=vd(l,"paddingRight"),m=vd(l,"paddingTop"),r=vd(l,"paddingBottom"),n=new td(parseFloat(m),parseFloat(k),parseFloat(r),parseFloat(n))),!H||9<=Number(zb)?(k=vd(l,"borderLeftWidth"),m=vd(l,"borderRightWidth"),r=vd(l,"borderTopWidth"),l=vd(l,"borderBottomWidth"),l=new td(parseFloat(r),
parseFloat(m),parseFloat(l),parseFloat(k))):(k=Od(l,"borderLeft"),m=Od(l,"borderRight"),r=Od(l,"borderTop"),l=Od(l,"borderBottom"),l=new td(r,m,l,k)),q.pixelWidth=z.width-l.left-n.left-n.right-l.right,q.pixelHeight=z.height-l.top-n.top-n.bottom-l.bottom):(q.pixelWidth=z.width,q.pixelHeight=z.height))));if(2!=e&&h&496){Ud(a,b^3,c,d,a.Qa&&0==e?1:2,f);return}!a.u||h&496||(e=parseFloat(a.g.style.left),f=parseFloat(a.g.style.top),C(!isNaN(e)&&!isNaN(f),"Could not parse position."),isFinite(e)&&0==e%1&&
isFinite(f)&&0==f%1||yd(a.g,Math.round(e),Math.round(f)))}Xd(a,b,c,d)},Xd=function(a,b,c,d){var e=a.m;Ab(a.l,function(f){qd(e,f)},a);od(e,a.l[b]);e.style.top=e.style.left=e.style.right=e.style.bottom="";a.h?(c=Ed(a.h,a.g),d=Yd(a.h,b),Vd(b)?e.style.top=Zd(c.y+d.y,a.g.offsetHeight-15)+"px":e.style.left=Zd(c.x+d.x,a.g.offsetWidth-15)+"px"):e.style[0==c?Vd(b)?"top":"left":Vd(b)?"bottom":"right"]=d+"px"},Zd=function(a,b){return 15>b?15:Math.min(Math.max(a,15),b)},Wd=function(a,b){switch(a){case 2:return 0==
b?1:5;case 1:return 0==b?0:4;case 0:return 0==b?12:13;default:return 0==b?8:9}},Yd=function(a,b){var c=0,d=0;a=Hd(a);switch(b){case 2:c=a.width/2;break;case 1:c=a.width/2;d=a.height;break;case 0:d=a.height/2;break;case 3:c=a.width,d=a.height/2}return new N(c,d)},Vd=function(a){return 0==a||3==a};g=Td.prototype;g.nb=!1;g.Sa=2;g.Ta=3;g.Ya=-5;g.Qa=!1;var $d,ae={Jb:"activedescendant",Ob:"atomic",Pb:"autocomplete",Rb:"busy",rb:"checked",Ub:"colindex",Zb:"controls",$b:"current",bc:"describedby",DISABLED:"disabled",fc:"dropeffect",hc:"expanded",ic:"flowto",kc:"grabbed",oc:"haspopup",qc:"hidden",sc:"invalid",tc:"label",uc:"labelledby",vc:"level",Ac:"live",Pc:"multiline",Qc:"multiselectable",Uc:"orientation",Vc:"owns",Wc:"posinset",Yc:"pressed",bd:"readonly",dd:"relevant",ed:"required",jd:"rowindex",ld:"selected",nd:"setsize",pd:"sort",Ed:"valuemax",
Fd:"valuemin",Gd:"valuenow",Hd:"valuetext"};var be={Kb:"alert",Lb:"alertdialog",Mb:"application",Nb:"article",Qb:"banner",Sb:"button",Tb:"checkbox",Vb:"columnheader",Wb:"combobox",Xb:"complementary",Yb:"contentinfo",ac:"definition",cc:"dialog",dc:"directory",ec:"document",jc:"form",lc:"grid",mc:"gridcell",nc:"group",pc:"heading",rc:"img",wc:"link",xc:"list",yc:"listbox",zc:"listitem",Bc:"log",Cc:"main",Dc:"marquee",Ec:"math",Fc:"menu",Gc:"menubar",Hc:"menuitem",Ic:"menuitemcheckbox",Jc:"menuitemradio",Rc:"navigation",Sc:"note",Tc:"option",
Xc:"presentation",Zc:"progressbar",$c:"radio",ad:"radiogroup",cd:"region",fd:"row",gd:"rowgroup",hd:"rowheader",kd:"scrollbar",SEARCH:"search",md:"separator",od:"slider",qd:"spinbutton",rd:"status",TAB:"tab",sd:"tablist",td:"tabpanel",ud:"textbox",vd:"textinfo",wd:"timer",xd:"toolbar",yd:"tooltip",zd:"tree",Ad:"treegrid",Bd:"treeitem"};var ce="combobox grid group listbox menu menubar radiogroup row rowgroup tablist textbox toolbar tree treegrid".split(" "),de=function(a,b){b?(C(Bb(be,b),"No such ARIA role "+b),a.setAttribute("role",b)):a.removeAttribute("role")},fe=function(a,b,c){Array.isArray(c)&&(c=c.join(" "));var d=ee(b);""===c||void 0==c?($d||($d={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",
busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=$d,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)},ge=function(a,b){a=a.getAttribute(ee(b));return null==a||void 0==a?"":String(a)},ie=function(a){var b=ge(a,"activedescendant");return O(a).getElementById(b)},ee=function(a){C(a,"ARIA attribute cannot be empty.");C(Bb(ae,a),"No such ARIA attribute "+a);return"aria-"+a};function je(a){a&&"function"==typeof a.va&&a.va()};var T=function(){this.O=this.O;this.G=this.G};T.prototype.O=!1;T.prototype.va=function(){this.O||(this.O=!0,this.v())};var ke=function(a,b){b=y(je,b);a.O?b():(a.G||(a.G=[]),a.G.push(b))};T.prototype.v=function(){if(this.G)for(;this.G.length;)this.G.shift()()};var le=function(a){T.call(this);this.h=a||P()};ha(le,T);le.prototype.m=function(){de(this.j(),"tooltip");fe(this.j(),"live","polite")};var me=function(a){le.call(this,a);this.g=this.h.Z("DIV","jfk-tooltip-contentId");this.l=this.h.Z("DIV","jfk-tooltip-arrow",this.h.Z("DIV","jfk-tooltip-arrowimplbefore"),this.h.Z("DIV","jfk-tooltip-arrowimplafter"));this.i=this.h.Z("DIV",{"class":"jfk-tooltip",role:"tooltip"},this.g,this.l);this.m()};ha(me,le);me.prototype.j=function(){return this.i};me.prototype.v=function(){le.prototype.v.call(this);this.i&&mc(this.i)};var ne=function(a){me.call(this,a)};ha(ne,me);ne.prototype.m=function(){de(this.j(),"tooltip")};var oe=function(a,b){this.type=a;this.i=this.target=b;this.defaultPrevented=this.m=!1};oe.prototype.o=function(){this.m=!0};oe.prototype.l=function(){this.defaultPrevented=!0};var pe=function(){if(!p.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{p.addEventListener("test",u,b),p.removeEventListener("test",u,b)}catch(c){}return a}();var qe={Na:"mousedown",Oa:"mouseup",fb:"mousecancel",Mc:"mousemove",Oc:"mouseover",Nc:"mouseout",Kc:"mouseenter",Lc:"mouseleave"};var U=function(a,b){oe.call(this,a?a.type:"");this.relatedTarget=this.i=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.g=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.u=!1;this.pointerId=0;this.pointerType="";this.h=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.i=b;(b=a.relatedTarget)?I&&(eb(b,"nodeName")||(b=null)):"mouseover"==
c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.g=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;
this.metaKey=a.metaKey;this.u=L?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:re[a.pointerType]||"";this.state=a.state;this.h=a;a.defaultPrevented&&U.s.l.call(this)}};A(U,oe);var re=Gc({2:"touch",3:"pen",4:"mouse"});U.prototype.o=function(){U.s.o.call(this);this.h.stopPropagation?this.h.stopPropagation():this.h.cancelBubble=!0};
U.prototype.l=function(){U.s.l.call(this);var a=this.h;a.preventDefault?a.preventDefault():a.returnValue=!1};var se="closure_listenable_"+(1E6*Math.random()|0),te=function(a){return!(!a||!a[se])};var ue=0;var ve=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Ea=e;this.key=++ue;this.removed=this.ya=!1},we=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Ea=null};var xe=function(a){this.src=a;this.g={};this.h=0};xe.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var h=ye(a,b,d,e);-1<h?(b=a[h],c||(b.ya=!1)):(b=new ve(b,this.src,f,!!d,e),b.ya=c,a.push(b));return b};xe.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.g))return!1;var e=this.g[a];b=ye(e,b,c,d);return-1<b?(we(e[b]),C(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.g[a],this.h--),!0):!1};
var ze=function(a,b){var c=b.type;if(c in a.g){var d=a.g[c],e=Ia(d,b),f;if(f=0<=e)C(null!=d.length),Array.prototype.splice.call(d,e,1);f&&(we(b),0==a.g[c].length&&(delete a.g[c],a.h--))}};xe.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.g)if(!a||c==a){for(var d=this.g[c],e=0;e<d.length;e++)++b,we(d[e]);delete this.g[c];this.h--}return b};
var Ae=function(a,b,c,d,e){a=a.g[b.toString()];b=-1;a&&(b=ye(a,c,d,e));return-1<b?a[b]:null},ye=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.Ea==d)return e}return-1};var Be="closure_lm_"+(1E6*Math.random()|0),Ce={},De=0,Fe=function(a,b,c,d,e){if(d&&d.once)return Ee(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)Fe(a,b[f],c,d,e);return null}c=Ge(c);return te(a)?a.listen(b,c,v(d)?!!d.capture:!!d,e):He(a,b,c,!1,d,e)},He=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=v(e)?!!e.capture:!!e,k=Ie(a);k||(a[Be]=k=new xe(a));c=k.add(b,c,d,h,f);if(c.proxy)return c;d=Je();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)pe||(e=h),void 0===
e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Ke(b.toString()),d);else if(a.addListener&&a.removeListener)C("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");De++;return c},Je=function(){var a=Le,b=function(c){return a.call(b.src,b.listener,c)};return b},Ee=function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)Ee(a,b[f],c,d,e);return null}c=Ge(c);return te(a)?
a.m.add(String(b),c,!0,v(d)?!!d.capture:!!d,e):He(a,b,c,!0,d,e)},Me=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Me(a,b[f],c,d,e);else d=v(d)?!!d.capture:!!d,c=Ge(c),te(a)?a.m.remove(String(b),c,d,e):a&&(a=Ie(a))&&(b=Ae(a,b,c,d,e))&&Ne(b)},Ne=function(a){if("number"!==typeof a&&a&&!a.removed){var b=a.src;if(te(b))ze(b.m,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Ke(c),d):b.addListener&&b.removeListener&&
b.removeListener(d);De--;(c=Ie(b))?(ze(c,a),0==c.h&&(c.src=null,b[Be]=null)):we(a)}}},Ke=function(a){return a in Ce?Ce[a]:Ce[a]="on"+a},Le=function(a,b){if(a.removed)a=!0;else{b=new U(b,this);var c=a.listener,d=a.Ea||a.src;a.ya&&Ne(a);a=c.call(d,b)}return a},Ie=function(a){a=a[Be];return a instanceof xe?a:null},Oe="__closure_events_fn_"+(1E9*Math.random()>>>0),Ge=function(a){C(a,"Listener can not be null.");if("function"===typeof a)return a;C(a.handleEvent,"An object listener must have handleEvent method.");
a[Oe]||(a[Oe]=function(b){return a.handleEvent(b)});return a[Oe]};var V=function(){T.call(this);this.m=new xe(this);this.tb=this;this.Y=null};A(V,T);V.prototype[se]=!0;g=V.prototype;g.Za=function(a){this.Y=a};g.removeEventListener=function(a,b,c,d){Me(this,a,b,c,d)};
g.J=function(a){Pe(this);var b=this.Y;if(b){var c=[];for(var d=1;b;b=b.Y)c.push(b),C(1E3>++d,"infinite loop")}b=this.tb;d=a.type||a;if("string"===typeof a)a=new oe(a,b);else if(a instanceof oe)a.target=a.target||b;else{var e=a;a=new oe(d,b);Db(a,e)}e=!0;if(c)for(var f=c.length-1;!a.m&&0<=f;f--){var h=a.i=c[f];e=Qe(h,d,!0,a)&&e}a.m||(h=a.i=b,e=Qe(h,d,!0,a)&&e,a.m||(e=Qe(h,d,!1,a)&&e));if(c)for(f=0;!a.m&&f<c.length;f++)h=a.i=c[f],e=Qe(h,d,!1,a)&&e;return e};
g.v=function(){V.s.v.call(this);this.m&&this.m.removeAll(void 0);this.Y=null};g.listen=function(a,b,c,d){Pe(this);return this.m.add(String(a),b,!1,c,d)};var Qe=function(a,b,c,d){b=a.m.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.removed&&h.capture==c){var k=h.listener,l=h.Ea||h.src;h.ya&&ze(a.m,h);e=!1!==k.call(l,d)&&e}}return e&&!d.defaultPrevented},Pe=function(a){C(a.m,"Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?")};var Re=function(a,b,c){if("function"===typeof a)c&&(a=x(a,c));else if(a&&"function"==typeof a.handleEvent)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:p.setTimeout(a,b||0)};var Se=function(a,b,c){T.call(this);this.g=a;this.l=b||0;this.h=c;this.i=x(this.xb,this)};A(Se,T);g=Se.prototype;g.S=0;g.v=function(){Se.s.v.call(this);this.stop();delete this.g;delete this.h};g.start=function(a){this.stop();this.S=Re(this.i,void 0!==a?a:this.l)};g.stop=function(){0!=this.S&&p.clearTimeout(this.S);this.S=0};g.xb=function(){this.S=0;this.g&&this.g.call(this.h)};var W=function(a){T.call(this);this.T=a;this.m={}};A(W,T);var Te=[];W.prototype.listen=function(a,b,c,d){Array.isArray(b)||(b&&(Te[0]=b.toString()),b=Te);for(var e=0;e<b.length;e++){var f=Fe(a,b[e],c||this.handleEvent,d||!1,this.T||this);if(!f)break;this.m[f.key]=f}return this};
var Ue=function(a,b,c,d,e,f){if(Array.isArray(c))for(var h=0;h<c.length;h++)Ue(a,b,c[h],d,e,f);else d=d||a.handleEvent,e=v(e)?!!e.capture:!!e,f=f||a.T||a,d=Ge(d),e=!!e,c=te(b)?Ae(b.m,String(c),d,e,f):b?(b=Ie(b))?Ae(b,c,d,e,f):null:null,c&&(Ne(c),delete a.m[c.key]);return a};W.prototype.removeAll=function(){Ab(this.m,function(a,b){this.m.hasOwnProperty(b)&&Ne(a)},this);this.m={}};W.prototype.v=function(){W.s.v.call(this);this.removeAll()};
W.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Xe=function(a){return Tb(Qa(a.replace(Ve,function(b,c){return We.test(c)?"":" "}).replace(/[\t\n ]+/g," ")))},We=/^(?:abbr|acronym|address|b|em|i|small|strong|su[bp]|u)$/i,Ve=/<[!\/]?([a-z0-9]+)([\/ ][^>]*)?>/gi;var Ye={},Ze=function(a){W.call(this);this.X=a;this.K=new Se(this.ra,0,this);ke(this,this.K);var b=window;this.u="function"===typeof b.MutationObserver?new b.MutationObserver(x(this.ma,this)):null;a=a.g;this.listen(a,"mouseout mousedown click blur focusout keydown".split(" "),this.P,!0);this.listen(a,["mouseover","focus","focusin"],this.qa,!0)};ha(Ze,W);Ze.prototype.v=function(){$e(this);W.prototype.v.call(this)};
var af=function(a,b){switch(b.type){case "mousedown":case "mouseover":case "mouseout":case "click":a.Y=!1;break;case "keydown":a.Y=!0}};Ze.prototype.qa=function(a){this.u&&this.u.disconnect();af(this,a);var b=a.target;a="focus"==a.type||"focusin"==a.type;var c=this.g&&nc(this.g.g,b);if(this.Y||!a||c){this.na=a;if(a=b&&b.getAttribute&&this.u)a=b.getAttribute("role")||null,a=Ka(ce,a);a&&(this.u.observe(b,{attributes:!0}),(a=ie(b))&&(b=a));this.i=b}else this.i=null;bf(this)};
Ze.prototype.P=function(a){af(this,a);var b=a.target;a="mousedown"==a.type||"click"==a.type;b=this.g&&nc(this.g.g,b);a&&b||(this.i=null,bf(this))};Ze.prototype.ma=function(a){Ja(a,x(function(b){var c=ie(b.target);c&&"aria-activedescendant"==b.attributeName&&(this.i=c,bf(this))},this))};var bf=function(a){if(0==a.K.S||!a.h||!a.o){$e(a);var b=null!=a.o?a.o:50;a.K.start(a.h?b:300)}},$e=function(a){a.C&&(p.clearTimeout(a.C),a.C=0,a.h=null)};
Ze.prototype.ra=function(){if(!this.i)cf(this),this.o=this.h=null;else if(!(this.h&&this.g&&nc(this.g.j(),this.i))||this.h.getAttribute("data-tooltip-unhoverable")){var a=uc(this.i,function(k){return k.getAttribute&&(k.getAttribute("data-tooltip-contained")||k.getAttribute("data-tooltip")||k.g)&&!k.getAttribute("data-tooltip-suspended")}),b=!1;this.h&&this.h!=a&&(cf(this),this.o=this.h=null,b=!0);if(!this.h&&a&&(this.h=a,df(this,a))){var c=Kb;if(a.getAttribute("data-tooltip-contained"))for(var d=
Zb(a),e=0;e<d.length;e++){if(d[e].parentNode==a){c=d[e].cloneNode(!0);break}}else c=a.g?a.g:Jb(a.getAttribute("data-tooltip"));d=a.getAttribute("data-tooltip-align");e=a.getAttribute("data-tooltip-class");var f=a.getAttribute("data-tooltip-offset");f=Pa(Vb(f))?-1:Number(f);var h=a.getAttribute("data-tooltip-hide-delay");h=Pa(Vb(h))?null:Number(h);if(!b&&(a=a.getAttribute("data-tooltip-delay"),a=Math.max(0,a-300))){this.C=Re(y(this.L,this.h,c,d,f,e,h),a,this);return}this.L(this.h,c,d,f,e,h)}}};
var df=function(a,b){return b.getAttribute("data-tooltip-only-on-overflow")&&b.offsetWidth>=b.scrollWidth&&b.offsetHeight>=b.scrollHeight||a.na&&"mouse"==b.getAttribute("data-tooltip-trigger")?!1:!0},ef=function(a){if(a)switch(a.toLowerCase().split(",")[0]){case "l":return 0;case "t":return 2;case "r":return 3}return 1};
Ze.prototype.L=function(a,b,c,d,e,f){this.C=0;this.o=f;if(!this.g){this.g=new ne(this.X);cf(this);f=this.X.g.body;var h=this.g.j();C(null!=f&&null!=h,"goog.dom.appendChild expects non-null arguments");f.appendChild(h);ke(this,this.g);this.l=new Td("jfk-tooltip",!0);this.l.nb=!0;this.l.Qa=!0;f=this.l;h=this.g.j();var k=this.g.l;f.g=h;f.m=k}a:{if(c)switch(c.toLowerCase().split(",")[1]){case "l":h=0;break a;case "r":h=1;break a}h=2}f=this.l;c=ef(c);null!=c&&(f.Ta=c);null!=h&&(f.Sa=h);"number"===typeof d&&
(f.Ya=d);qd(this.g.j(),"jfk-tooltip-hide");this.D!=e&&(this.D&&!Pa(Vb(this.D))&&qd(this.g.j(),this.D),Pa(Vb(e))||od(this.g.j(),e),this.D=e);yd(this.g.j(),0,0);if(b instanceof M){d=this.g.g;if(null!==d&&void 0!==d.tagName){if("script"===d.tagName.toLowerCase())throw Error("Use setTextContent with a SafeScript.");if("style"===d.tagName.toLowerCase())throw Error("Use setTextContent with a SafeStyleSheet.");}d.innerHTML=Gb(b)}else for(lc(this.g.g);d=b.firstChild;)this.g.g.appendChild(d);this.l.h=a;this.l.o()};
var cf=function(a){a.g&&od(a.g.j(),"jfk-tooltip-hide")};var ff=[],gf=function(a){C(!Object.isSealed(a),"Cannot use getInstance() with a sealed constructor.");var b="ha";if(a.ha&&a.hasOwnProperty(b))return a.ha;ff.push(a);var c=new a;a.ha=c;C(a.hasOwnProperty(b),"Could not instantiate singleton.");return c};var kf=function(a,b,c,d,e,f){if(L&&e)return hf(a);if(e&&!d)return!1;if(!I){"number"===typeof b&&(b=jf(b));var h=17==b||18==b||L&&91==b;if((!c||L)&&h||L&&16==b&&(d||f))return!1}if((K||ib)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(H&&d&&b==a)return!1;switch(a){case 13:return I?f||e?!1:!(c&&d):!0;case 27:return!(K||ib||I)}return I&&(d||e||f)?!1:hf(a)},hf=function(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=
a||(K||ib)&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:case 163:case 58:return!0;case 173:return I;default:return!1}},jf=function(a){if(I)a=lf(a);else if(L&&K)switch(a){case 93:a=91}return a},lf=function(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};var mf=function(a,b,c,d){U.call(this,d);this.type="key";this.g=a;this.repeat=c};A(mf,U);var nf=function(a,b){V.call(this);a&&this.attach(a,b)};A(nf,V);g=nf.prototype;g.ia=null;g.Fa=null;g.Xa=null;g.Ga=null;g.H=-1;g.aa=-1;g.Ra=!1;
var of={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},pf={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},qf=L&&I;g=nf.prototype;
g.Db=function(a){if(K||ib)if(17==this.H&&!a.ctrlKey||18==this.H&&!a.altKey||L&&91==this.H&&!a.metaKey)this.aa=this.H=-1;-1==this.H&&(a.ctrlKey&&17!=a.g?this.H=17:a.altKey&&18!=a.g?this.H=18:a.metaKey&&91!=a.g&&(this.H=91));kf(a.g,this.H,a.shiftKey,a.ctrlKey,a.altKey,a.metaKey)?(this.aa=jf(a.g),qf&&(this.Ra=a.altKey)):this.handleEvent(a)};g.Fb=function(a){this.aa=this.H=-1;this.Ra=a.altKey};
g.handleEvent=function(a){var b=a.h,c=b.altKey;if(H&&"keypress"==a.type){var d=this.aa;var e=13!=d&&27!=d?b.keyCode:0}else(K||ib)&&"keypress"==a.type?(d=this.aa,e=0<=b.charCode&&63232>b.charCode&&hf(d)?b.charCode:0):("keypress"==a.type?(qf&&(c=this.Ra),b.keyCode==b.charCode?32>b.keyCode?(d=b.keyCode,e=0):(d=this.aa,e=b.charCode):(d=b.keyCode||this.aa,e=b.charCode||0)):(d=b.keyCode||this.aa,e=b.charCode||0),L&&63==e&&224==d&&(d=191));var f=d=jf(d);d?63232<=d&&d in of?f=of[d]:25==d&&a.shiftKey&&(f=
9):b.keyIdentifier&&b.keyIdentifier in pf&&(f=pf[b.keyIdentifier]);if(!I||"keypress"!=a.type||kf(f,this.H,a.shiftKey,a.ctrlKey,c,a.metaKey))a=f==this.H,this.H=f,b=new mf(f,e,a,b),b.altKey=c,this.J(b)};g.j=function(){return this.ia};g.attach=function(a,b){this.Ga&&this.detach();this.ia=a;this.Fa=Fe(this.ia,"keypress",this,b);this.Xa=Fe(this.ia,"keydown",this.Db,b,this);this.Ga=Fe(this.ia,"keyup",this.Fb,b,this)};
g.detach=function(){this.Fa&&(Ne(this.Fa),Ne(this.Xa),Ne(this.Ga),this.Ga=this.Xa=this.Fa=null);this.ia=null;this.aa=this.H=-1};g.v=function(){nf.s.v.call(this);this.detach()};var rf=function(){};ia(rf);rf.prototype.g=0;var tf=function(a){V.call(this);this.i=a||P();this.Ma=sf;this.S=null;this.N=!1;this.h=null;this.u=void 0;this.T=this.na=this.l=null;this.ib=!1};A(tf,V);tf.prototype.ub=rf.$();
var sf=null,uf=function(a,b){switch(a){case 1:return b?"disable":"enable";case 2:return b?"highlight":"unhighlight";case 4:return b?"activate":"deactivate";case 8:return b?"select":"unselect";case 16:return b?"check":"uncheck";case 32:return b?"focus":"blur";case 64:return b?"open":"close"}throw Error("Invalid component state");},vf=function(a,b){if(a.l&&a.l.T){var c=a.l.T,d=a.S;d in c&&delete c[d];c=a.l.T;if(null!==c&&b in c)throw Error('The object already contains the key "'+b+'"');c[b]=a}a.S=b};
tf.prototype.j=function(){return this.h};var wf=function(a){a=a.h;C(a,"Can not call getElementStrict before rendering/decorating.");return a},xf=function(a){return a.h?$b("jfk-checkbox-checkmark",a.h||a.i.g):null},yf=function(a){a.u||(a.u=new W(a));return C(a.u)};tf.prototype.Za=function(a){if(this.l&&this.l!=a)throw Error("Method not supported");tf.s.Za.call(this,a)};tf.prototype.ma=function(){this.h=ic(this.i.g,"DIV")};
var zf=function(a,b){if(a.N)throw Error("Component already rendered");a.h||a.ma();b?b.insertBefore(a.h,null):a.i.g.body.appendChild(a.h);a.l&&!a.l.N||a.U()},Af=function(a,b){if(a.N)throw Error("Component already rendered");if(b&&a.ab(b)){a.ib=!0;var c=O(b);a.i&&a.i.g==c||(a.i=P(b));a.Aa(b);a.U()}else throw Error("Invalid element to decorate");};g=tf.prototype;g.ab=function(){return!0};g.Aa=function(a){this.h=a};g.U=function(){this.N=!0;Bf(this,function(a){!a.N&&a.j()&&a.U()})};
g.wa=function(){Bf(this,function(a){a.N&&a.wa()});this.u&&this.u.removeAll();this.N=!1};g.v=function(){this.N&&this.wa();this.u&&(this.u.va(),delete this.u);Bf(this,function(a){a.va()});!this.ib&&this.h&&mc(this.h);this.l=this.h=this.T=this.na=null;tf.s.v.call(this)};var Bf=function(a,b){a.na&&a.na.forEach(b,void 0)};var Cf=function(){},Df;ia(Cf);var Ff=function(){var a=new Ef;a.A=function(){return"jfk-checkbox"};return a},Gf={button:"pressed",checkbox:"checked",menuitem:"selected",menuitemcheckbox:"checked",menuitemradio:"checked",radio:"checked",tab:"selected",treeitem:"selected"};g=Cf.prototype;g.oa=function(){};g.fa=function(a){return a.i.Z("DIV",Hf(this,a).join(" "),a.getContent())};g.pa=function(a){return a};g.bb=function(){return!0};
g.M=function(a,b){b.id&&vf(a,b.id);var c=this.pa(b);c&&c.firstChild?If(a,c.firstChild.nextSibling?La(c.childNodes):c.firstChild):a.ua=null;var d=0,e=this.A(),f=this.A(),h=!1,k=!1,l=La(ld(b));l.forEach(function(q){h||q!=e?k||q!=f?d|=Jf(this,q):k=!0:(h=!0,f==e&&(k=!0));1==Jf(this,q)&&(Aa(c),c.hasAttribute("tabindex")&&rc(c)&&qc(c,!1))},this);a.B=d;h||(l.push(e),f==e&&(k=!0));k||l.push(f);(a=a.Ua)&&l.push.apply(l,a);h&&k&&!a||md(b,l.join(" "));return b};
g.mb=function(a){null==a.Ma&&(a.Ma=Jd(a.N?a.h:a.i.g.body));a.Ma&&this.eb(a.j(),!0);a.isEnabled()&&this.Ha(a,a.isVisible())};var Kf=function(a,b){if(a=a.oa()){C(b,"The element passed as a first parameter cannot be null.");var c=b.getAttribute("role")||null;a!=c&&de(b,a)}};g=Cf.prototype;
g.Ja=function(a,b){var c=!b;b=H?a.getElementsByTagName("*"):null;if(Kd){if(c=c?"none":"",a.style&&(a.style[Kd]=c),b){a=0;for(var d;d=b[a];a++)d.style&&(d.style[Kd]=c)}}else if(H&&(c=c?"on":"",a.setAttribute("unselectable",c),b))for(a=0;d=b[a];a++)d.setAttribute("unselectable",c)};g.eb=function(a,b){var c=this.A()+"-rtl";(a=a.j?a.j():a)&&(b?pd:rd)(a,[c])};g.cb=function(a){var b;return a.F&32&&(b=a.j())?b.hasAttribute("tabindex")&&rc(b):!1};
g.Ha=function(a,b){var c;if(a.F&32&&(c=a.j())){if(!b&&a.B&32){try{c.blur()}catch(d){}a.B&32&&a.jb(null)}(c.hasAttribute("tabindex")&&rc(c))!=b&&qc(c,b)}};g.Ka=function(a,b,c){var d=a.j();if(d){var e=Lf(this,b);e&&(a=a.j?a.j():a)&&(c?pd:rd)(a,[e]);this.W(d,b,c)}};
g.W=function(a,b,c){Df||(Df={1:"disabled",8:"selected",16:"checked",64:"expanded"});C(a,"The element passed as a first parameter cannot be null.");b=Df[b];var d=a.getAttribute("role")||null;d&&(d=Gf[d]||b,b="checked"==b||"selected"==b?d:b);b&&fe(a,b,c)};g.A=function(){return"goog-control"};
var Hf=function(a,b){var c=a.A(),d=[c],e=a.A();e!=c&&d.push(e);c=b.getState();for(e=[];c;){var f=c&-c;e.push(Lf(a,f));c&=~f}d.push.apply(d,e);(a=b.Ua)&&d.push.apply(d,a);return d},Lf=function(a,b){a.g||Mf(a);return a.g[b]},Jf=function(a,b){if(!a.D){a.g||Mf(a);var c=a.g,d={},e;for(e in c)d[c[e]]=e;a.D=d}a=parseInt(a.D[b],10);return isNaN(a)?0:a},Mf=function(a){var b=a.A();var c=-1!=b.replace(/\xa0|\s/g," ").indexOf(" ");C(!c,"ControlRenderer has an invalid css class: '"+b+"'");a.g={1:b+"-disabled",
2:b+"-hover",4:b+"-active",8:b+"-selected",16:b+"-checked",32:b+"-focused",64:b+"-open"}};var Nf=function(){};A(Nf,Cf);ia(Nf);g=Nf.prototype;g.oa=function(){return"button"};g.W=function(a,b,c){switch(b){case 8:case 16:C(a,"The button DOM element cannot be null.");fe(a,"pressed",c);break;default:case 64:case 1:Nf.s.W.call(this,a,b,c)}};g.fa=function(a){var b=Nf.s.fa.call(this,a);this.Ia(b,a.xa());var c=a.R();c&&this.La(b,c);a.F&16&&this.W(b,16,a.V());return b};g.M=function(a,b){b=Nf.s.M.call(this,a,b);var c=this.R(b);a.gb=c;a.D=this.xa(b);a.F&16&&this.W(b,16,a.V());return b};g.R=u;
g.La=u;g.xa=function(a){return a.title};g.Ia=function(a,b){a&&(b?a.title=b:a.removeAttribute("title"))};g.A=function(){return"goog-button"};var Of=function(a,b){if(!a)throw Error("Invalid class name "+a);if("function"!==typeof b)throw Error("Invalid decorator function "+b);},Pf={};var Y=function(a,b,c){tf.call(this,c);if(!b){for(b=this.constructor;b;){var d=na(b);if(d=Pf[d])break;b=(b=Object.getPrototypeOf(b.prototype))&&b.constructor}b=d?"function"===typeof d.$?d.$():new d:null}this.g=b;this.ua=void 0!==a?a:null};A(Y,tf);g=Y.prototype;g.ua=null;g.B=0;g.F=39;g.ga=255;g.qb=!0;g.Ua=null;g.Ca=!0;var Rf=function(a){a.N&&0!=a.Ca&&Qf(a,!1);a.Ca=!1};
Y.prototype.ma=function(){var a=this.g.fa(this);this.h=a;Kf(this.g,a);this.g.Ja(a,!1);this.isVisible()||(a.style.display="none",a&&fe(a,"hidden",!0))};Y.prototype.ab=function(a){return this.g.bb(a)};Y.prototype.Aa=function(a){this.h=a=this.g.M(this,a);Kf(this.g,a);this.g.Ja(a,!1);this.qb="none"!=a.style.display};
Y.prototype.U=function(){Y.s.U.call(this);var a=this.g,b=wf(this);C(this);C(b);this.isVisible()||fe(b,"hidden",!this.isVisible());this.isEnabled()||a.W(b,1,!this.isEnabled());this.F&8&&a.W(b,8,this.isSelected());this.F&16&&a.W(b,16,this.V());this.F&64&&a.W(b,64,!!(this.B&64));this.g.mb(this);this.F&-2&&(this.Ca&&Qf(this,!0),this.F&32&&(a=this.j()))&&(b=this.C||(this.C=new nf),b.attach(a),yf(this).listen(b,"key",this.Eb).listen(a,"focus",this.Cb).listen(a,"blur",this.jb))};
var Qf=function(a,b){var c=yf(a),d=a.j();b?(c.listen(d,qe.Na,a.ca).listen(d,[qe.Oa,qe.fb],a.ka).listen(d,"mouseover",a.ra).listen(d,"mouseout",a.qa),a.X!=u&&c.listen(d,"contextmenu",a.X),H&&(wb(9)||c.listen(d,"dblclick",a.lb),a.K||(a.K=new Sf(a),ke(a,a.K)))):(Ue(Ue(Ue(Ue(c,d,qe.Na,a.ca),d,[qe.Oa,qe.fb],a.ka),d,"mouseover",a.ra),d,"mouseout",a.qa),a.X!=u&&Ue(c,d,"contextmenu",a.X),H&&(wb(9)||Ue(c,d,"dblclick",a.lb),je(a.K),a.K=null))};
Y.prototype.wa=function(){Y.s.wa.call(this);this.C&&this.C.detach();this.isVisible()&&this.isEnabled()&&this.g.Ha(this,!1)};Y.prototype.v=function(){Y.s.v.call(this);this.C&&(this.C.va(),delete this.C);delete this.g;this.K=this.Ua=this.ua=null};Y.prototype.getContent=function(){return this.ua};var If=function(a,b){a.ua=b};Y.prototype.isVisible=function(){return this.qb};Y.prototype.isEnabled=function(){return!(this.B&1)};
Y.prototype.setEnabled=function(a){var b=this.l;b&&"function"==typeof b.isEnabled&&!b.isEnabled()||!Tf(this,1,!a)||(a||(Uf(this,!1),Vf(this,!1)),this.isVisible()&&this.g.Ha(this,a),Wf(this,1,!a,!0))};var Vf=function(a,b){Tf(a,2,b)&&Wf(a,2,b)},Uf=function(a,b){Tf(a,4,b)&&Wf(a,4,b)};g=Y.prototype;g.isSelected=function(){return!!(this.B&8)};g.$a=function(a){Tf(this,8,a)&&Wf(this,8,a)};g.V=function(){return!!(this.B&16)};g.da=function(a){Tf(this,16,a)&&Wf(this,16,a)};
g.la=function(a){Tf(this,32,a)&&Wf(this,32,a)};g.getState=function(){return this.B};var Wf=function(a,b,c,d){d||1!=b?a.F&b&&c!=!!(a.B&b)&&(a.g.Ka(a,b,c),a.B=c?a.B|b:a.B&~b):a.setEnabled(!c)},Xf=function(a,b,c){if(a.N&&a.B&b&&!c)throw Error("Component already rendered");!c&&a.B&b&&Wf(a,b,!1);a.F=c?a.F|b:a.F&~b},Z=function(a,b){return!!(a.ga&b)&&!!(a.F&b)},Tf=function(a,b,c){return!!(a.F&b)&&!!(a.B&b)!=c&&(!(0&b)||a.J(uf(b,c)))&&!a.O};
Y.prototype.ra=function(a){!Yf(a,this.j())&&this.J("enter")&&this.isEnabled()&&Z(this,2)&&Vf(this,!0)};Y.prototype.qa=function(a){!Yf(a,this.j())&&this.J("leave")&&(Z(this,4)&&Uf(this,!1),Z(this,2)&&Vf(this,!1))};Y.prototype.X=u;var Yf=function(a,b){return!!a.relatedTarget&&nc(b,a.relatedTarget)};g=Y.prototype;g.ca=function(a){this.isEnabled()&&(Z(this,2)&&Vf(this,!0),0!=a.h.button||L&&a.ctrlKey||(Z(this,4)&&Uf(this,!0),this.g&&this.g.cb(this)&&this.j().focus()));0!=a.h.button||L&&a.ctrlKey||a.l()};
g.ka=function(a){this.isEnabled()&&(Z(this,2)&&Vf(this,!0),this.B&4&&this.ba(a)&&Z(this,4)&&Uf(this,!1))};g.lb=function(a){this.isEnabled()&&this.ba(a)};g.ba=function(a){Z(this,16)&&this.da(!this.V());Z(this,8)&&this.$a(!0);if(Z(this,64)){var b=!(this.B&64);Tf(this,64,b)&&Wf(this,64,b)}b=new oe("action",this);a&&(b.altKey=a.altKey,b.ctrlKey=a.ctrlKey,b.metaKey=a.metaKey,b.shiftKey=a.shiftKey,b.u=a.u);return this.J(b)};g.Cb=function(){Z(this,32)&&this.la(!0)};
g.jb=function(){Z(this,4)&&Uf(this,!1);Z(this,32)&&this.la(!1)};g.Eb=function(a){return this.isVisible()&&this.isEnabled()&&this.ja(a)?(a.l(),a.o(),!0):!1};g.ja=function(a){return 13==a.g&&this.ba(a)};if("function"!==typeof Y)throw Error("Invalid component class "+Y);if("function"!==typeof Cf)throw Error("Invalid renderer class "+Cf);var Zf=na(Y);Pf[Zf]=Cf;Of("goog-control",function(){return new Y(null)});
var Sf=function(a){T.call(this);this.h=a;this.g=!1;this.i=new W(this);ke(this,this.i);a=wf(this.h);this.i.listen(a,qe.Na,this.m).listen(a,qe.Oa,this.o).listen(a,"click",this.l)};A(Sf,T);var $f=!H||9<=Number(zb);Sf.prototype.m=function(){this.g=!1};Sf.prototype.o=function(){this.g=!0};
var ag=function(a,b){if(!$f)return a.button=0,a.type=b,a;var c=document.createEvent("MouseEvents");c.initMouseEvent(b,a.bubbles,a.cancelable,a.view||null,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,a.relatedTarget||null);return c};Sf.prototype.l=function(a){if(this.g)this.g=!1;else{var b=a.h,c=b.button,d=b.type,e=ag(b,"mousedown");this.h.ca(new U(e,a.i));e=ag(b,"mouseup");this.h.ka(new U(e,a.i));$f||(b.button=c,b.type=d)}};
Sf.prototype.v=function(){this.h=null;Sf.s.v.call(this)};var bg=function(){};A(bg,Nf);ia(bg);g=bg.prototype;g.oa=function(){};
g.fa=function(a){Rf(a);a.ga&=-256;Xf(a,32,!1);var b=a.i,c=b.Z,d={"class":Hf(this,a).join(" "),disabled:!a.isEnabled(),title:a.xa()||"",value:a.R()||""};if(a=a.getContent()){if("string"!==typeof a)if(Array.isArray(a))a=a.map(tc).join("");else{var e=[];sc(a,e,!0);a=e.join("");a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");a=a.replace(/ +/g," ");" "!=a&&(a=a.replace(/^\s*/,""))}a=a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")}else a="";return c.call(b,"BUTTON",
d,a||"")};g.bb=function(a){return"BUTTON"==a.tagName||"INPUT"==a.tagName&&("button"==a.type||"submit"==a.type||"reset"==a.type)};g.M=function(a,b){Rf(a);a.ga&=-256;Xf(a,32,!1);if(b.disabled){var c=ya(Lf(this,1));od(b,c)}return bg.s.M.call(this,a,b)};g.mb=function(a){yf(a).listen(a.j(),"click",a.ba)};g.Ja=u;g.eb=u;g.cb=function(a){return a.isEnabled()};g.Ha=u;g.Ka=function(a,b,c){bg.s.Ka.call(this,a,b,c);(a=a.j())&&1==b&&(a.disabled=c)};g.R=function(a){return a.value};
g.La=function(a,b){a&&(a.value=b)};g.W=u;var cg=function(a,b,c){Y.call(this,a,b||bg.$(),c)};A(cg,Y);g=cg.prototype;g.R=function(){return this.gb};g.xa=function(){return this.D};g.Ia=function(a){this.D=a;this.g.Ia(this.j(),a)};g.v=function(){cg.s.v.call(this);delete this.gb;delete this.D};g.U=function(){cg.s.U.call(this);if(this.F&32){var a=this.j();a&&yf(this).listen(a,"keyup",this.ja)}};g.ja=function(a){return 13==a.g&&"key"==a.type||32==a.g&&"keyup"==a.type?this.ba(a):32==a.g};Of("goog-button",function(){return new cg(null)});var eg=function(a,b,c,d){cg.call(this,a,dg.$(),b);this.L=c||0;this.P=d||0;this.Pa=!1};A(eg,cg);g=eg.prototype;
g.Ia=function(a){this.D=a;var b=this.j();if(b)if(this.Pa){var c=a instanceof M?Xe(Gb(a).toString()):a;b.removeAttribute("title");b.removeAttribute("data-tooltip-contained");b.removeAttribute("data-tooltip");a?(a instanceof M?b.g=a:(b.setAttribute("data-tooltip",a),b.g=null),b.setAttribute("aria-label",c)):(b.g=null,b.removeAttribute("aria-label"));a=P(b)||P();b=na(a.g);Ye[b]||(Ye[b]=new Ze(a))}else a?b.title=a:b.removeAttribute("title")};
g.setEnabled=function(a){this.isEnabled()!=a&&(eg.s.setEnabled.call(this,a),fg(this))};g.la=function(a){eg.s.la.call(this,a);gg(this,!1)};g.ca=function(a){eg.s.ca.call(this,a);this.isEnabled()&&gg(this,!0)};g.ka=function(a){eg.s.ka.call(this,a);this.isEnabled()&&gg(this,!0)};
var gg=function(a,b){a.j()&&(a=a.j(),b?od(a,"jfk-button-clear-outline"):qd(a,"jfk-button-clear-outline"))},fg=function(a){a.j()&&hg(a.g,a)},dg=function(){this.C=this.A()+"-standard";this.h=this.A()+"-action";this.O=this.A()+"-primary";this.m=this.A()+"-default";this.o=this.A()+"-flat";this.G=this.A()+"-narrow";this.u=this.A()+"-mini";this.l=this.A()+"-contrast"};A(dg,Nf);dg.$=function(){return gf(dg)};g=dg.prototype;g.ea=function(a,b,c){a&&c.L!=a&&(c.L=a,fg(c));b&&c.P!=b&&(c.P=b,fg(c))};g.A=function(){return"jfk-button"};
g.fa=function(a){Ca(a,eg,"Button is expected to be instance of jfk.Button");var b=a.i,c=Xc($c,{disabled:!a.isEnabled(),checked:a.V(),style:a.L,title:a.xa(),Ib:a.Pa,value:a.R(),width:a.P},b);b.sb(c,a.getContent());this.M(a,c);return c};
g.M=function(a,b){dg.s.M.call(this,a,b);this.i||(this.i=Eb(this.C,y(this.ea,0,null),this.h,y(this.ea,2,null),this.O,y(this.ea,3,null),this.m,y(this.ea,1,null),this.o,y(this.ea,4,null),this.u,y(this.ea,5,null),this.l,y(this.ea,6,null),this.G,y(this.ea,null,1)));for(var c=ld(b),d=0;d<c.length;++d){var e=this.i[c[d]];e&&e(a)}if(c=b.getAttribute("data-tooltip"))a.D=c,a.Pa=!0;return b};g.R=function(a){return a.getAttribute("value")||""};g.La=function(a,b){a&&a.setAttribute("value",b)};
var hg=function(a,b){function c(h,k){(h?d:e).push(k)}C(b.j(),"Button element must already exist when updating style.");var d=[],e=[],f=b.L;c(0==f,a.C);c(2==f,a.h);c(3==f,a.O);c(4==f,a.o);c(5==f,a.u);c(1==f,a.m);c(6==f,a.l);c(1==b.P,a.G);c(!b.isEnabled(),a.A()+"-disabled");rd(b.j(),e);pd(b.j(),d)};var ig=function(a,b){a=a||{};var c=a.attributes;var d=a.sa,e=a.checked,f=a.disabled,h=a.id,k=a.ob,l=a.pb,q=a.vb;a=a.wb;Vc();Mc["jfk.templates.checkbox.main"]?c=Mc["jfk.templates.checkbox.main"]({attributes:c,sa:d,checked:e,disabled:f,id:h,ob:k,pb:l,vb:q,wb:a},b):(b=l?" "+S("jfk-checkbox-undetermined"):e?" "+S("jfk-checkbox-checked"):" "+S("jfk-checkbox-unchecked"),e=l?"mixed":e?"true":"false",q=a?' aria-labelledby="'+S(a)+'"':q?' aria-label="'+S(q)+'"':"",c=Ic('<span class="'+S("jfk-checkbox")+" "+
S("goog-inline-block")+b+(f?" "+S("jfk-checkbox-disabled"):"")+(d?" "+S(d):"")+'" role="checkbox" aria-checked="'+e+'"'+q+(h?' id="'+S(h)+'"':"")+(f?' aria-disabled="true" tabindex="-1"':' tabindex="'+(k?S(k):"0")+'"')+(c?Tc(Sc(c)):"")+' dir="ltr"><div class="'+S("jfk-checkbox-checkmark")+'" role="presentation"></div></span>'));return c};var Ef=function(){};A(Ef,Cf);ia(Ef);Ef.prototype.fa=function(a){var b=a.i.Z("SPAN",Hf(this,a).join(" "));jg(this,b,a.o);return b};Ef.prototype.M=function(a,b){b=Ef.s.M.call(this,a,b);C(b);var c=ld(b),d=!1;Ka(c,kg(this,null))?d=null:Ka(c,kg(this,!0))?d=!0:Ka(c,kg(this,!1))&&(d=!1);a.o=d;C(b,"The element cannot be null.");fe(b,"checked",null==d?"mixed":1==d?"true":"false");return b};Ef.prototype.oa=function(){return"checkbox"};
var jg=function(a,b,c){if(b){C(b);var d=kg(a,c);C(d);C(b);nd(b,d)||(Ab(lg,function(e){e=kg(this,e);C(b);e==d?od(b,e):qd(b,e)},a),fe(b,"checked",null==c?"mixed":1==c?"true":"false"))}};Ef.prototype.A=function(){return"goog-checkbox"};var kg=function(a,b){a=a.A();if(1==b)return a+"-checked";if(0==b)return a+"-unchecked";if(null==b)return a+"-undetermined";throw Error("Invalid checkbox state: "+b);};var mg=function(a,b,c){c=c||Ef.$();Y.call(this,null,c,b);this.o=void 0!==a?a:!1};A(mg,Y);var lg={rb:!0,Cd:!1,Dd:null};g=mg.prototype;g.I=null;g.V=function(){return 1==this.o};g.da=function(a){a!=this.o&&(this.o=a,jg(this.g,this.j(),this.o))};
g.U=function(){mg.s.U.call(this);if(this.Ca){var a=yf(this);this.I&&a.listen(this.I,"click",this.Va).listen(this.I,"mouseover",this.ra).listen(this.I,"mouseout",this.qa).listen(this.I,"mousedown",this.ca).listen(this.I,"mouseup",this.ka);a.listen(this.j(),"click",this.Va)}a=wf(this);if(this.I&&a!=this.I&&Pa(ge(a,"label"))){if(!this.I.id){var b=this.I;var c=(this.S||(this.S=":"+(this.ub.g++).toString(36)))+".lbl";b.id=c}fe(a,"labelledby",this.I.id)}};
g.Va=function(a){a.o();var b=this.o?"uncheck":"check";this.isEnabled()&&!a.target.href&&this.J(b)&&(a.l(),this.da(this.o?!1:!0),this.J("change"))};g.ja=function(a){32==a.g&&(this.ba(a),this.Va(a));return!1};Of("goog-checkbox",function(){return new mg});var ng=function(a,b){var c=Ff();mg.call(this,a,b,c);Xf(this,4,!0)};ha(ng,mg);ng.prototype.ma=function(){this.h=Xc(ig,{checked:this.V(),disabled:!this.isEnabled(),pb:null==this.o},this.i)};ng.prototype.Aa=function(a){mg.prototype.Aa.call(this,a);od(a,"goog-inline-block");this.j().dir="ltr";xf(this)||(a=this.i.Z("DIV","jfk-checkbox-checkmark"),this.j().appendChild(a));a=xf(this);C(a,"Expected element in component with class: %s","jfk-checkbox-checkmark");de(a,"presentation")};
ng.prototype.la=function(a){mg.prototype.la.call(this,a);og(this,!1)};ng.prototype.ca=function(a){mg.prototype.ca.call(this,a);this.isEnabled()&&og(this,!0)};var og=function(a,b){a.j()&&(a=a.j(),b?od(a,"jfk-checkbox-clearOutline"):qd(a,"jfk-checkbox-clearOutline"))};var pg=function(a,b){a=a||{};var c=a.attributes,d=a.checked,e=a.sa,f=a.disabled,h=a.id,k=a.label,l=a.name;a=a.value;Vc();return Mc["jfk.templates.radiobutton.strict"]?Mc["jfk.templates.radiobutton.strict"]({attributes:c,checked:d,sa:e,disabled:f,id:h,label:k,name:l,value:a},b):Ic('<div class="'+S("jfk-radiobutton")+(d?" "+S("jfk-radiobutton-checked"):"")+(f?" "+S("jfk-radiobutton-disabled"):"")+(e?" "+S(e):"")+'"'+(l?' data-name="'+S(l)+'"':"")+(a?' data-value="'+S(a)+'"':"")+(h?' id="'+S(h)+'"':
"")+(c?Tc(Sc(c)):"")+' role="radio"><span class="'+S("jfk-radiobutton-radio")+'"></span><span class="'+S("jfk-radiobutton-label")+'">'+(k?Lc(k):"")+"</span></div>")};var sg=function(a,b,c,d){Y.call(this,null,qg.$(),a);this.P=c||"";this.L=d||"";Xf(this,16,!0);this.ga&=-17;b&&rg(this,b)};ha(sg,Y);sg.prototype.ba=function(a){this.da(!0);return Y.prototype.ba.call(this,a)};sg.prototype.ja=function(a){switch(a.g){case 38:case 37:return this.J(a.ctrlKey?"b":"d"),!0;case 40:case 39:return this.J(a.ctrlKey?"a":"c"),!0;case 32:return this.ba(a);case 9:return this.J(a.shiftKey?"g":"f"),!1}return Y.prototype.ja.call(this,a)};sg.prototype.R=function(){return this.P};
var tg=function(a,b){a.L=b;(a=a.j())&&a.setAttribute("data-name",b)};sg.prototype.da=function(a){Y.prototype.da.call(this,a)};sg.prototype.setEnabled=function(a){Y.prototype.setEnabled.call(this,a);this.J("e")};var rg=function(a,b){a.hb=b;var c=a.j();c&&(b=a.hb,a=a.g.pa(c),C(a),lc(a),kc(a,b))},qg=function(){};ha(qg,Cf);g=qg.prototype;g.fa=function(a){var b=Xc(pg,{checked:a.V(),disabled:!a.isEnabled(),name:a.L,value:a.R()},a.i);if(a=a.hb){var c=this.pa(b);C(c);lc(c);kc(c,a)}return b};
g.M=function(a,b){Cf.prototype.M.call(this,a,b);var c=b.getAttribute("data-value");if(c){a.P=c;var d=a.j();d&&d.setAttribute("data-value",c)}(c=b.getAttribute("data-name"))&&tg(a,c);c=this.pa(b);C(c);c.firstChild?rg(a,c.firstChild.nextSibling?La(c.childNodes):c.firstChild):rg(a,null);return b};g.oa=function(){return"radio"};g.pa=function(a){return $b(this.A()+"-label",a)};g.A=function(){return"jfk-radiobutton"};qg.$=function(){return gf(qg)};var vg=function(a){V.call(this);this.g=[];ug(this,a)};A(vg,V);vg.prototype.h=null;vg.prototype.i=null;var ug=function(a,b){b&&(b.forEach(function(c){wg(this,c,!1)},a),Ma(a.g,b))};vg.prototype.clear=function(){var a=this.g;if(!Array.isArray(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0;this.h=null};vg.prototype.v=function(){vg.s.v.call(this);delete this.g;this.h=null};var wg=function(a,b,c){b&&("function"==typeof a.i?a.i(b,c):"function"==typeof b.$a&&b.$a(c))};var yg=function(a,b){V.call(this);this.i=b||"";this.g=new vg;ke(this,this.g);this.h=new W(this);ke(this,this.h);this.g.i=xg;this.h.listen(this.g,"select",y(this.J,"change"));this.h.listen(this,"a",this.zb);this.h.listen(this,"b",this.Ab);this.h.listen(this,"c",this.Bb);this.h.listen(this,"d",this.Gb);this.h.listen(this,"e",this.Da);this.h.listen(this,"f",y(this.kb,!1));this.h.listen(this,"g",y(this.kb,!0));a&&Ja(a,this.l,this)};ha(yg,V);
yg.prototype.l=function(a){C(null!=a);this.h.listen(a,"action",this.yb);a.Za(this);tg(a,this.i);var b=a.V(),c=this.g,d=c.g.length;a&&(wg(c,a,!1),Na(c.g,d,0,a));b&&zg(this,a);a.j()&&this.Da()};
var zg=function(a,b){var c=a.g;b!=c.h&&(wg(c,c.h,!1),c.h=b,wg(c,b,!0));c.J("select");a.Da()},Ag=function(a){return(a=a.g.h)?a.R():null},Bg=function(a,b,c){var d=a.g.g[b]||null;c&&zg(a,d);Ja(La(a.g.g),function(e){e.j()&&qc(e.j(),d==e)});try{d.j().focus()}catch(e){}},Dg=function(a,b,c,d){c=Cg(a,b,c);-1!=c&&a.g.g[c]&&(qc(b.j(),!1),Bg(a,c,d))},Cg=function(a,b,c){var d=a.g.g.length;b=b?a.g.g.indexOf(b):-1;for(var e=1;e<=d;e++){var f=(b+c*e)%d;f=0>f*d?f+d:f;if((a.g.g[f]||null).isEnabled())return f}return-1};
g=yg.prototype;g.Gb=function(a){a=a.target;C(a);Dg(this,a,-1,!0)};g.Bb=function(a){a=a.target;C(a);Dg(this,a,1,!0)};g.Ab=function(a){a=a.target;C(a);Dg(this,a,-1,!1)};g.zb=function(a){a=a.target;C(a);Dg(this,a,1,!1)};g.kb=function(a,b){b=this.Da(b);try{var c=b[a?0:1];c&&c.j().focus()}catch(d){}};
g.Da=function(){var a=this.g.h,b=this.g.g[0]||null,c=a&&a.isEnabled(),d=c?a:b;C(d,"Must have at least one button in the group");d.isEnabled()||(a=Cg(this,d,1),d=-1!=a?this.g.g[a]||null:null);var e=d;d&&!c&&(a=Cg(this,d,-1),e=-1!=a?this.g.g[a]||null:null);Ja(La(this.g.g),function(f){f.j()&&qc(f.j(),d==f||e==f)});return[d,e]};g.yb=function(a){a=a.target;zg(this,a);try{a.j().focus()}catch(b){}};g.v=function(){Ja(La(this.g.g),function(a){je(a)});V.prototype.v.call(this)};
var xg=function(a,b){a.da(b);a.j()&&qc(a.j(),b)};var Fg=function(){this.g=new wc;this.l=Q("targetLangSel");Eg();this.T=new eg;Af(this.T,Q("saveBtn"));this.K=new eg;Af(this.K,Q("resetBtn"));this.u=Q("saveStatus");this.C=new sg(void 0,B("MSG_OPTIONS_ICON_DESC"),"1");this.O=new sg(void 0,B("MSG_OPTIONS_POPUP_DESC"),"2");this.D=new sg(void 0,B("MSG_OPTIONS_NONE_DESC"),"0");var a=Q("popup-option-content");zf(this.C,a);if(!zc){this.m=hc("DIV","popup-option-ai");Q("popup-option-content").appendChild(this.m);this.i=new ng;this.o=hc("SPAN","popup-option-ai-lbl");
R(this.o,B("MSG_OPTIONS_ALWAYS_SHOW_ICON"));a=this.i;var b=this.o;if(a.N){var c=!!(a.B&32);a.wa();a.I=b;a.U();c&&wf(a).focus()}else a.I=b;zf(this.i,this.m);this.m.appendChild(this.o)}a=Q("popup-option-content");zf(this.O,a);a=hc("DIV","popup-option-tip",B("MSG_OPTIONS_POPUP_TIP"));Q("popup-option-content").appendChild(a);a=Q("popup-option-content");zf(this.D,a);a=hc("DIV","popup-option-tip",B("MSG_OPTIONS_NONE_TIP"));Q("popup-option-content").appendChild(a);this.h=new yg([this.C,this.O,this.D])};
Fg.prototype.G=function(){if(this.g.loaded){Eg();Gg(this);for(var a=this.h.g.g.length,b=0;b<a;++b){var c=this.h.g.g[b]||null;if(c.R()==this.g.h){zg(this.h,c);break}}this.l.addEventListener("change",x(this.P,this));Fe(this.h,"change",this.Y,!1,this);zc||(this.i.da(!this.g.i),zc||this.i.setEnabled("1"==Ag(this.h)),Fe(this.i,"change",this.X,!1,this));Fe(this.T,"action",this.L,!1,this);Fe(this.K,"action",function(){window.history.go(0)})}else Re(this.G,50,this)};
var Gg=function(a){var b=0;a:{var c=a.g.m;break a;throw Error("Invalid input for getLangList()");}var d=a.g;if(""!=d.g)d=d.g;else a:{for(var e=0;e<d.l.length;e++){var f=ra(d.l[e]);if(d.m[f]){d=f;break a}}d="en"}d=d||"";for(var h in c)e=document.createElement("option"),e.value=h,e.text=c[h],e.h=b++,a.l.appendChild(e),h==d&&(e.selected=!0)};Fg.prototype.P=function(){this.g.g=this.l.value};
Fg.prototype.Y=function(){zc||this.i.setEnabled("1"==Ag(this.h));if(null!=Ag(this.h)){var a=Ag(this.h);this.g.h=a}};Fg.prototype.X=function(){this.g.i=!this.i.V()};Fg.prototype.L=function(){yc(this.g);this.u.style.display="";this.u.style.setProperty("-webkit-transition","opacity 0.4s ease-out");this.u.style.opacity=1;window.setTimeout(function(){document.getElementById("saveStatus").style.opacity=0},1500)};
var Eg=function(){R(Q("options-page-title"),B("MSG_OPTIONS_PAGE_TITLE"));R(Q("options-title-heading"),B("MSG_OPTIONS_TITLE"));R(Q("lang-option"),B("MSG_OPTIONS_LANG"));R(Q("popup-option"),B("MSG_OPTIONS_POPUP"));R(Q("popup-option-title"),B("MSG_OPTIONS_POPUP_TITLE"));R(Q("saveBtn"),B("MSG_OPTIONS_SAVE"));R(Q("resetBtn"),B("MSG_OPTIONS_RESET"));R(Q("saveStatus"),B("MSG_OPTIONS_SAVED_STATUS"));R(Q("footer-homepage"),B("MSG_OPTIONS_FOOTER_HOMEPAGE"));R(Q("footer-privacy"),B("MSG_OPTIONS_FOOTER_PRIVACY"))};
document.addEventListener("DOMContentLoaded",function(){(new Fg).G()});})();
